export function Hero() {
    return (
        <section className="relative z-10 px-6 pt-36 pb-14 md:pb-20">
            <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.95fr_1.05fr]">
                <div>
                    <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-black/5 bg-white/70 px-4 py-2 text-sm text-black/60 shadow-sm backdrop-blur-xl">
                        <span className="h-2 w-2 rounded-full bg-emerald-500 shadow-[0_0_18px_rgba(16,185,129,0.7)]" />
                        AI meal planning for busy weeks
                    </div>

                    <h1 className="max-w-3xl text-5xl font-bold leading-[1.02] tracking-[-0.06em] text-[#14120f] md:text-7xl">
                        Plan your meals.
                        <br />
                        <span className="bg-gradient-to-r from-orange-600 via-amber-500 to-rose-500 bg-clip-text text-transparent">
                            Shop smarter.
                        </span>
                    </h1>

                    <p className="mt-6 max-w-xl text-lg leading-8 text-black/55">
                        PlatePilot helps you create daily and weekly meal plans, organize
                        recipes, calculate ingredients and build a clean shopping list in
                        minutes.
                    </p>

                    <div className="mt-9 flex flex-col gap-3 sm:flex-row">
                        <a
                            href="#planner"
                            className="rounded-full bg-[#14120f] px-7 py-3 text-center text-sm font-semibold text-white shadow-xl shadow-black/10 transition hover:-translate-y-0.5 hover:bg-black"
                        >
                            Generate meal plan
                        </a>

                        <a
                            href="#preview"
                            className="rounded-full border border-black/10 bg-white/60 px-7 py-3 text-center text-sm font-semibold text-black/70 backdrop-blur-xl transition hover:-translate-y-0.5 hover:bg-white"
                        >
                            View demo
                        </a>
                    </div>

                    <div className="mt-10 flex flex-wrap gap-6 text-sm text-black/45">
                        <div>
                            <span className="font-bold text-black">7 days</span> meal plans
                        </div>
                        <div>
                            <span className="font-bold text-black">30+</span> recipe ideas
                        </div>
                        <div>
                            <span className="font-bold text-black">1 list</span> for shopping
                        </div>
                    </div>
                </div>

                <div id="preview">
                    <div className="relative">
                        <div className="absolute -inset-6 rounded-[2.5rem] bg-gradient-to-br from-orange-300/45 via-amber-200/50 to-rose-200/35 blur-3xl" />
                        <div className="relative rounded-[2rem] border border-black/5 bg-white/75 p-4 shadow-2xl shadow-black/10 backdrop-blur-xl">
                            <div className="rounded-[1.5rem] border border-black/5 bg-[#fffaf3] p-5">
                                <div className="mb-5 flex items-center justify-between">
                                    <div>
                                        <p className="text-sm font-semibold text-black">
                                            Weekly plan
                                        </p>
                                        <p className="text-xs text-black/45">
                                            Balanced meals generated by AI
                                        </p>
                                    </div>

                                    <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">
                                        Ready
                                    </span>
                                </div>

                                <div className="grid gap-3">
                                    {["Monday", "Tuesday", "Wednesday"].map((day, index) => (
                                        <div
                                            key={day}
                                            className="rounded-2xl border border-black/5 bg-white p-4 shadow-sm"
                                        >
                                            <div className="mb-3 flex items-center justify-between">
                                                <span className="text-sm font-semibold text-black">
                                                    {day}
                                                </span>
                                                <span className="text-xs text-black/40">
                                                    {index === 0 ? "2,140 kcal" : index === 1 ? "2,020 kcal" : "2,260 kcal"}
                                                </span>
                                            </div>

                                            <div className="grid gap-2 sm:grid-cols-3">
                                                {["Breakfast", "Lunch", "Dinner"].map((meal) => (
                                                    <div
                                                        key={meal}
                                                        className="rounded-xl bg-orange-50 px-3 py-3"
                                                    >
                                                        <p className="text-xs font-medium text-orange-700">
                                                            {meal}
                                                        </p>
                                                        <p className="mt-1 text-xs text-black/55">
                                                            {meal === "Breakfast"
                                                                ? "Greek yogurt bowl"
                                                                : meal === "Lunch"
                                                                    ? "Chicken rice bowl"
                                                                    : "Salmon veggie plate"}
                                                        </p>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}